// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuG2R-lBK3VBOrQz2CvnFPaEsp4MW8jt8',
    appId: '1:962723076181:web:5ad69d276070c70b041cdc',
    messagingSenderId: '962723076181',
    projectId: 'resident-management-811f8',
    authDomain: 'resident-management-811f8.firebaseapp.com',
    storageBucket: 'resident-management-811f8.appspot.com',
    measurementId: 'G-KTLV1BF1LL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfdlNqseyodbGSDfyuME9bMn4Th56ZgHI',
    appId: '1:962723076181:android:8e6960194df010fa041cdc',
    messagingSenderId: '962723076181',
    projectId: 'resident-management-811f8',
    storageBucket: 'resident-management-811f8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkVYl-YhNxKyu7KhBa9_-G4mWA7F2arpo',
    appId: '1:962723076181:ios:3c4885b7a0e1d1d7041cdc',
    messagingSenderId: '962723076181',
    projectId: 'resident-management-811f8',
    storageBucket: 'resident-management-811f8.appspot.com',
    iosBundleId: 'com.tqq.mepartments',
  );
}
